import test from 'node:test';
import assert from 'node:assert/strict';
import { createDatabase } from '../src/database.js';
import { CommerceService } from '../src/commerce-service.js';
import { DomainService } from '../src/domain-service.js';
import { PostgresSyncDatabase } from '../src/postgres-sync-database.js';

async function exerciseDomainLifecycle(db, storeId, domainId) {
  let reachable = false;
  const options = {
    cnameTarget: 'edge.example.com', requireOwnershipTxt: false,
    dnsResolver: { async resolve4() { return ['192.0.2.40']; } },
    sslProvider: { async provisionDomain() { return { status: reachable ? 'active' : 'pending' }; } },
  };
  const domains = new DomainService(db, options);
  const checked = await domains.checkDns(storeId, domainId);
  assert.equal(checked.dnsReady, true);
  assert.ok(checked.verifiedAt);
  assert.ok(checked.ownershipVerifiedAt);
  const pending = await domains.verifyDomain(storeId, domainId);
  assert.equal(pending.overallStatus, 'PENDING_SSL');
  assert.equal(pending.verifiedAt, checked.verifiedAt);
  assert.equal(pending.ownershipVerifiedAt, checked.ownershipVerifiedAt);
  reachable = true;
  const synced = await domains.syncPendingDomains();
  assert.equal(synced.length, 1);
  assert.equal(synced[0].overallStatus, 'ACTIVE');
  const rechecked = await domains.checkDns(storeId, domainId);
  assert.equal(rechecked.overallStatus, 'ACTIVE');
  assert.equal(rechecked.routingStatus, 'active');
  assert.equal(domains.resolveHost('merchant.example').storeId, storeId);

  const aRecord = new DomainService(db, { ...options, apexTarget: '192.0.2.40' });
  assert.equal((await aRecord.checkDns(storeId, domainId)).dnsReady, true);
  const wrongRecord = new DomainService(db, { ...options, apexTarget: '192.0.2.41' });
  assert.equal((await wrongRecord.checkDns(storeId, domainId)).dnsReady, false);
  assert.equal(wrongRecord.resolveHost('merchant.example'), null);
}

test('domain checks preserve activation and support explicit apex A records', async () => {
  const db = createDatabase(':memory:');
  try {
    const store = new CommerceService(db).createStore({ name: 'Domain QA', slug: 'domain-qa' });
    const domain = new DomainService(db, { cnameTarget: 'edge.example.com' })
      .addDomain(store.id, { domainName: 'merchant.example' });
    await exerciseDomainLifecycle(db, store.id, domain.id);
  } finally { db.close(); }
});

test('PostgreSQL domain verification supports legacy text and migrated timestamp columns', {
  skip: !process.env.TEST_POSTGRES_URL,
}, async () => {
  const db = new PostgresSyncDatabase(process.env.TEST_POSTGRES_URL);
  const template = createDatabase(':memory:');
  try {
    // Session-local tables shadow public tables; never mutate a configured database's data.
    db.exec('CREATE TEMP TABLE stores (id INTEGER PRIMARY KEY, name TEXT, slug TEXT)');
    for (const name of ['custom_domains', 'domain_audit_log']) {
      const { sql } = template.prepare('SELECT sql FROM sqlite_master WHERE name=?').get(name);
      db.exec(sql.replace(/^CREATE TABLE/i, 'CREATE TEMP TABLE')
        .replace(/\bid INTEGER PRIMARY KEY/i, 'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'));
    }
    for (const column of ['ownership_verified_at', 'last_checked_at'])
      db.exec(`ALTER TABLE custom_domains ALTER COLUMN ${column} TYPE TIMESTAMP USING ${column}::timestamp`);
    db.exec("INSERT INTO stores VALUES (1,'Domain QA','domain-qa')");
    db.exec(`INSERT INTO custom_domains (id,store_id,domain_name,normalized_hostname,verification_token,cname_target,txt_name,txt_value)
      VALUES (1,1,'merchant.example','merchant.example','qa-token','edge.example.com','_commera2.merchant.example','qa-token')`);
    assert.throws(() => db.exec('SELECT COALESCE(verified_at,CURRENT_TIMESTAMP) FROM custom_domains'),
      { code: '42804' });
    await exerciseDomainLifecycle(db, 1, 1);
  } finally { template.close(); await db.close(); }
});
