import test from 'node:test';
import assert from 'node:assert/strict';
import { createDatabase } from '../src/database.js';
import { createApp } from '../src/server.js';
async function call(base,path,method='GET',data){const response=await fetch(base+path,{method,headers:{'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)}),type=response.headers.get('content-type')||'';return{response,body:type.includes('json')?await response.json():await response.text()};}
async function product(base,storeId,name,slug){return (await call(base,`/api/stores/${storeId}/products`,'POST',{name,slug,pricePaise:79900,stock:10})).body;}

test('default and special policy rules drive authoritative return and cancellation eligibility',async t=>{
 const db=createDatabase(':memory:'),app=createApp({db,port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;
 let r=await call(base,'/api/stores','POST',{name:'Nivkara',slug:'nivkara'}),store=r.body;const oil=await product(base,store.id,'Hair Oil','hair-oil'),serum=await product(base,store.id,'Hair Serum','hair-serum');r=await call(base,'/api/stores','POST',{name:'Other',slug:'other'});const other=r.body,otherProduct=await product(base,other.id,'Other Product','other-product');
 const collection=Number(db.prepare("INSERT INTO collections(store_id,name,slug) VALUES (?,?,?)").run(store.id,'Personal Care','personal-care').lastInsertRowid);db.prepare('INSERT INTO collection_products(collection_id,product_id) VALUES (?,?)').run(collection,serum.id);
 r=await call(base,`/api/stores/${store.id}/policies/rules/default`,'PATCH',{allowReturns:true,returnWindowDays:3,allowCancellation:true,cancellationUntil:'before_fulfillment',cancellationWindowHours:0,returnShippingFeePaise:25000,restockingChargePaise:0,codOrdersEligible:true,deliveredOrdersEligible:true,damagedProductReturn:true,wrongProductReturn:true});assert.equal(r.response.status,200);assert.equal(r.body.returnWindowDays,3);
 const context={productId:oil.id,paymentMethod:'cod',fulfillmentStatus:'Unfulfilled',deliveryStatus:'Delivered',orderCreatedAt:'2026-08-25T00:00:00Z',deliveredAt:'2026-08-26T00:00:00Z',now:'2026-08-28T00:00:00Z',reason:'standard'};
 r=await call(base,`/api/stores/${store.id}/policies/rules/evaluate`,'POST',context);assert.equal(r.body.ruleSource,'default');assert.equal(r.body.return.eligible,true);assert.equal(r.body.return.feePaise,25000);assert.equal(r.body.cancellation.eligible,true);
 r=await call(base,`/api/stores/${store.id}/policies/rules/evaluate`,'POST',{...context,deliveryStatus:'Not Shipped'});assert.equal(r.body.return.eligible,false);assert.match(r.body.return.reason,/delivered/i);
 r=await call(base,`/api/stores/${store.id}/policies/rules/evaluate`,'POST',{...context,now:'2026-08-30T00:00:00Z',fulfillmentStatus:'Fulfilled'});assert.equal(r.body.return.eligible,false);assert.match(r.body.return.reason,/window/i);assert.equal(r.body.cancellation.eligible,false);
 r=await call(base,`/api/stores/${store.id}/policies/rules`,'POST',{ruleName:'Personal Care Products',appliesTo:'collection',targetId:collection,returnAllowed:true,returnDays:7,returnCondition:'damaged_only',cancellationAllowed:false,status:'active'});assert.equal(r.response.status,201);const rule=r.body;assert.equal(rule.ruleName,'Personal Care Products');
 r=await call(base,`/api/stores/${store.id}/policies/rules/evaluate`,'POST',{...context,productId:serum.id,reason:'standard'});assert.equal(r.body.ruleSource,'special');assert.equal(r.body.ruleId,rule.id);assert.equal(r.body.return.eligible,false);assert.match(r.body.return.reason,/damaged/i);assert.equal(r.body.cancellation.eligible,false);
 r=await call(base,`/api/stores/${store.id}/policies/rules/evaluate`,'POST',{...context,productId:serum.id,reason:'damaged'});assert.equal(r.body.return.eligible,true);
 r=await call(base,`/api/stores/${store.id}/policies/rules`);assert.equal(r.body.length,1);r=await call(base,`/api/stores/${store.id}/policies/rules`,'POST',{ruleName:'Cross Store',appliesTo:'product',targetId:otherProduct.id,returnAllowed:true,returnDays:2,cancellationAllowed:true,status:'active'});assert.equal(r.response.status,400);assert.match(r.body.error,/current store/i);
});

test('written policies move from no policy to draft and published public pages with live privacy linkage',async t=>{
 const db=createDatabase(':memory:'),app=createApp({db,port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;let r=await call(base,'/api/stores','POST',{name:'Nivkara',slug:'nivkara'}),store=r.body;const oil=await product(base,store.id,'Hair Oil','hair-oil');r=await call(base,`/api/stores/${store.id}/pages`,'POST',{productId:oil.id,title:'Hair Ritual',slug:'ritual',body:'Daily ritual'});const page=r.body;await call(base,`/api/stores/${store.id}/pages/${page.id}/publish`,'POST',{});
 r=await call(base,`/api/stores/${store.id}/policies/written`);assert.equal(r.response.status,200);assert.equal(r.body.length,6);assert.ok(r.body.every(policy=>policy.status==='no_policy'));assert.deepEqual(r.body.map(policy=>policy.type),['return-refund','privacy','terms','shipping','legal','subscription']);
 r=await call(base,`/api/stores/${store.id}/policies/written/return-refund`,'PATCH',{title:'Return & Refund Policy',content:'<h2>Returns</h2><p>Returns are accepted within three days.</p><script>alert(1)</script>'});assert.equal(r.response.status,200);assert.equal(r.body.status,'draft');assert.doesNotMatch(r.body.content,/script/i);
 r=await call(base,`/s/nivkara/policies/return-refund`);assert.equal(r.response.status,404);r=await call(base,`/api/stores/${store.id}/policies/written/return-refund/preview`);assert.equal(r.response.status,200);assert.match(r.body,/Return &amp; Refund Policy/);assert.match(r.body,/<h2>Returns<\/h2>/);assert.doesNotMatch(r.body,/alert\(1\)/);
 r=await call(base,`/api/stores/${store.id}/policies/written/return-refund/publish`,'POST',{});assert.equal(r.body.status,'published');r=await call(base,`/s/nivkara/policies/return-refund`);assert.equal(r.response.status,200);assert.match(r.body,/Returns are accepted within three days/);
 await call(base,`/api/stores/${store.id}/settings/privacy`,'PATCH',{requireAnalyticsConsent:true,allowCustomerDataCollection:false});await call(base,`/api/stores/${store.id}/policies/written/privacy`,'PATCH',{title:'Privacy Policy',content:'<p>We protect customer information.</p>'});await call(base,`/api/stores/${store.id}/policies/written/privacy/publish`,'POST',{});r=await call(base,`/s/nivkara/policies/privacy`);assert.match(r.body,/Analytics consent required/);assert.match(r.body,/Customer data collection disabled/);r=await call(base,`/api/stores/${store.id}/settings`);assert.equal(r.body.privacy.privacyPolicyLink,'/s/nivkara/policies/privacy');
 await call(base,`/api/stores/${store.id}/policies/written/contact`,'PATCH',{title:'Contact Information',contact:{storeName:'Nivkara',supportEmail:'support@nivkara.com',phone:'+91 9876543210',address:'Ahmedabad, Gujarat',supportHours:'Monday to Saturday'}});await call(base,`/api/stores/${store.id}/policies/written/contact/publish`,'POST',{});r=await call(base,`/s/nivkara/policies/contact`);assert.match(r.body,/support@nivkara.com/);
 await call(base,`/api/stores/${store.id}/policies/written/shipping`,'PATCH',{title:'Shipping Policy',content:'<p>Delivery takes three to five days.</p>'});r=await call(base,'/s/nivkara/ritual');assert.match(r.body,/Return Policy/);assert.match(r.body,/Privacy Policy/);assert.match(r.body,/Contact Information/);assert.doesNotMatch(r.body,/href="\/s\/nivkara\/policies\/shipping"/);r=await call(base,`/api/stores/${store.id}/policies/written`);assert.equal(r.body.find(item=>item.type==='shipping').status,'draft');assert.equal(r.body.find(item=>item.type==='legal').status,'no_policy');
});

test('Policy dashboard exposes operational rules and all written policy editing states',async t=>{
 const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;let r=await call(base,'/api/stores','POST',{name:'Nivkara',slug:'nivkara'}),store=r.body;await product(base,store.id,'Hair Oil','hair-oil');const [index,script,dashboard]=await Promise.all([call(base,'/'),call(base,'/app.js'),call(base,`/api/stores/${store.id}/dashboard`)]);assert.match(index.body,/data-view="policies">Policy</);for(const text of ['Return & Cancellation Rules','Default Rules','Add Rule','Allow Returns','Return Window','Allow Cancellation','Cancellation Window','Return Shipping Fee','Restocking / Return Charge','COD Orders Eligible','Delivered Orders Eligible','Damaged Product Return','Wrong Product Return','All Products','Specific Product','Specific Collection','Written Policy','No Policy Set','Draft','Published','Rich Text Editor','Edit','Save','Preview','Publish'])assert.ok(script.body.includes(text)||script.body.includes(text.replaceAll('&','&amp;')),`Missing ${text}`);assert.ok(dashboard.body.policies);assert.equal(dashboard.body.policies.written.length,6);assert.deepEqual(dashboard.body.policies.written.map(item=>item.label),['Return Policy','Privacy Policy','Terms of Service','Shipping Policy','Legal Notice','Subscription Policy']);assert.equal(dashboard.body.policies.rules.length,0);assert.equal(typeof dashboard.body.policies.defaultRules.allowReturns,'boolean');
});

test('order policy eligibility is calculated from persisted order and delivery facts',async t=>{
 const db=createDatabase(':memory:'),app=createApp({db,port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;let r=await call(base,'/api/stores','POST',{name:'Nivkara',slug:'nivkara'}),store=r.body;const oil=await product(base,store.id,'Hair Oil','hair-oil');r=await call(base,`/api/stores/${store.id}/pages`,'POST',{productId:oil.id,title:'Hair Ritual',slug:'ritual',body:'Daily ritual'});const page=r.body;await call(base,`/api/stores/${store.id}/policies/rules/default`,'PATCH',{allowReturns:true,returnWindowDays:3,allowCancellation:true,cancellationUntil:'before_fulfillment',codOrdersEligible:true,deliveredOrdersEligible:true,damagedProductReturn:true,wrongProductReturn:true});const customer=Number(db.prepare("INSERT INTO customers(store_id,name,phone,address) VALUES (?,?,?,?)").run(store.id,'Rahul','9876543210','Ahmedabad').lastInsertRowid);db.prepare('INSERT INTO checkout_sessions(id,store_id,page_id,product_id) VALUES (?,?,?,?)').run('policy-order',store.id,page.id,oil.id);const order=Number(db.prepare("INSERT INTO orders(store_id,order_number,customer_id,checkout_session_id,payment_method,channel,total_paise,payment_status,fulfillment_status,delivery_status,delivery_method) VALUES (?,?,?,?,?,'Online Store',79900,'Pending','Unfulfilled','Delivered','Courier')").run(store.id,'ORD-POLICY',customer,'policy-order','cod').lastInsertRowid);db.prepare('INSERT INTO order_items(order_id,product_id,name,quantity,unit_price_paise,line_total_paise) VALUES (?,?,?,?,?,?)').run(order,oil.id,'Hair Oil',1,79900,79900);const partner=Number(db.prepare("INSERT INTO delivery_partners(store_id,name,code) VALUES (?,?,?)").run(store.id,'Manual Carrier','manual-policy').lastInsertRowid);db.prepare("INSERT INTO shipments(store_id,order_id,partner_id,tracking_number,status,delivered_at) VALUES (?,?,?,?,'delivered',datetime('now','-1 day'))").run(store.id,order,partner,'AWB-POLICY');r=await call(base,`/api/stores/${store.id}/orders/${order}/policy-eligibility?reason=standard`);assert.equal(r.response.status,200);assert.equal(r.body.return.eligible,true);assert.equal(r.body.cancellation.eligible,true);db.prepare("UPDATE orders SET delivery_status='Not Shipped' WHERE id=?").run(order);r=await call(base,`/api/stores/${store.id}/orders/${order}/policy-eligibility?reason=standard`);assert.equal(r.body.return.eligible,false);assert.match(r.body.return.reason,/delivered/i);
});
