import test from 'node:test';
import assert from 'node:assert/strict';
import { createDatabase } from '../src/database.js';
import { CommerceService } from '../src/commerce-service.js';
import { ProjectService } from '../src/project-service.js';
import { pageTemplates } from '../src/page-templates.js';

function setup(options={}){const db=createDatabase(':memory:');const commerce=new CommerceService(db);const store=commerce.createStore({name:'Nivkara',slug:'nivkara'});const first=commerce.createProduct(store.id,{name:'Hair Oil',slug:'oil',pricePaise:99900,stock:10});const second=commerce.createProduct(store.id,{name:'Hair Mask',slug:'mask',pricePaise:79900,stock:8});return{db,commerce,store,first,second,projects:new ProjectService(db,options)}}

test('one store contains multiple products and multiple independent projects',()=>{const{projects,store,first,second}=setup();const a=projects.createProject(store.id,{name:'Hair Oil Funnel',slug:'oil-funnel',productId:first.id});const b=projects.createProject(store.id,{name:'Hair Mask Funnel',slug:'mask-funnel',productId:second.id});assert.deepEqual(projects.listProjects(store.id).map(p=>p.name),['Hair Mask Funnel','Hair Oil Funnel']);assert.notEqual(a.id,b.id);assert.equal(projects.getProject(store.id,a.id).productId,first.id)})

test('high-quality templates produce editable structured product pages',()=>{const{projects,store,first}=setup();const project=projects.createProject(store.id,{name:'Launch',slug:'launch',productId:first.id});const templates=projects.listTemplates();assert.ok(templates.length>=3);for(const template of templates){assert.ok(template.preview);assert.ok(template.designTokens);assert.ok(template.sections.length>=4)}const page=projects.createPageFromTemplate(store.id,{projectId:project.id,productId:first.id,templateKey:pageTemplates[0].key,title:'Oil Ritual',slug:'ritual'});assert.equal(page.creationMethod,'template');assert.equal(page.projectId,project.id);assert.equal(page.templateKey,pageTemplates[0].key);assert.equal(JSON.parse(page.contentJson).hero.headline,'Oil Ritual');assert.ok(JSON.parse(page.contentJson).sections.length>=4)})

test('pre-built HTML import is persisted but active content is removed',()=>{const{projects,store,first}=setup();const project=projects.createProject(store.id,{name:'Import',slug:'import',productId:first.id});const page=projects.importPrebuiltPage(store.id,{projectId:project.id,productId:first.id,title:'Imported Page',slug:'imported',html:'<main><h1 onclick="steal()">Safe title</h1><img src="x" onerror="steal()"><script>steal()</script><a href="javascript:steal()">Bad</a><a href=javascript:steal()>Unquoted</a><a href="java&#x73;cript:steal()">Encoded</a></main>'});assert.equal(page.creationMethod,'upload');assert.match(page.importedHtml,/Safe title/);assert.doesNotMatch(page.importedHtml,/script|onclick|onerror|javascript:|&#x73;/i);projects.publishPage(store.id,page.id);assert.equal(projects.getPublishedPage('nivkara','imported').page.status,'published')})

test('AI page creation has a truthful unavailable state when no provider is authorized',async()=>{const{projects,store,first}=setup();const project=projects.createProject(store.id,{name:'AI',slug:'ai',productId:first.id});assert.equal(projects.aiStatus().available,false);await assert.rejects(()=>projects.createAIPage(store.id,{projectId:project.id,productId:first.id,title:'AI Page',slug:'ai-page',brief:'Create a page'}),/not configured or authorized/i)})

test('authorized AI adapter output becomes an editable and publishable page',async()=>{let calls=0;const generator=async({product,title,brief})=>{calls++;return{hero:{eyebrow:'AYURVEDIC CARE',headline:title,subheadline:brief},sections:[{type:'benefits',title:'Benefits',items:['Lightweight','Easy ritual']},{type:'proof',title:'Why it works',body:product.name},{type:'cta',title:'Start today'}],ctaText:'Order COD'}};const{projects,store,first}=setup({aiGenerator:generator,aiProvider:{provider:'test-local',model:'fixture',authorized:true}});const project=projects.createProject(store.id,{name:'AI',slug:'ai',productId:first.id});const page=await projects.createAIPage(store.id,{projectId:project.id,productId:first.id,title:'AI Page',slug:'ai-page',brief:'A bedtime routine'});assert.equal(calls,1);assert.equal(page.creationMethod,'ai');assert.equal(JSON.parse(page.contentJson).hero.headline,'AI Page');projects.updatePageContent(store.id,page.id,{hero:{headline:'Edited headline'}});assert.equal(JSON.parse(projects.getPage(store.id,page.id).contentJson).hero.headline,'Edited headline');projects.publishPage(store.id,page.id);assert.equal(projects.getPublishedPage('nivkara','ai-page').page.status,'published')})

test('projects and pages are strictly scoped to their store',()=>{const{commerce,projects,store,first}=setup();const project=projects.createProject(store.id,{name:'Private',slug:'private',productId:first.id});const other=commerce.createStore({name:'Other',slug:'other'});assert.throws(()=>projects.getProject(other.id,project.id),/not found/i);assert.throws(()=>projects.createPageFromTemplate(other.id,{projectId:project.id,productId:first.id,templateKey:pageTemplates[0].key,title:'Cross store',slug:'cross'}),/not found/i)})
