import test from 'node:test';
import assert from 'node:assert/strict';
import { createDatabase } from '../src/database.js';
import { createApp } from '../src/server.js';

async function call(base,path,method='GET',data){const response=await fetch(base+path,{method,headers:{'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const type=response.headers.get('content-type')||'';return{response,body:type.includes('json')?await response.json():await response.text()};}
async function storefront(base){let result=await call(base,'/api/stores','POST',{name:'Nivkara',slug:'nivkara'});const store=result.body;result=await call(base,`/api/stores/${store.id}/products`,'POST',{name:'Hair Oil',slug:'hair-oil',pricePaise:79900,stock:20});const product=result.body;result=await call(base,`/api/stores/${store.id}/pages`,'POST',{productId:product.id,title:'Hair Ritual',slug:'ritual',body:'Daily ritual'});const page=result.body;await call(base,`/api/stores/${store.id}/pages/${page.id}/publish`,'POST',{});return{store,product,page};}

test('Settings COD Form persists and changes the real published checkout',async t=>{const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;const {store}=await storefront(base);
 const codForm={enabled:true,formName:'Primary COD',heading:'Enter Your Delivery Details',subheading:'Fast delivery across India',submitButtonText:'Confirm COD Order',addressAutofill:false,saveIncompleteCheckout:false,buttonEnabled:true,fields:{fullName:{show:true,required:true,label:'Your Full Name',placeholder:'Enter full name'},phone:{show:true,required:true,label:'Mobile Number',placeholder:'10-digit mobile'},alternatePhone:{show:false,required:false,label:'Alternate Phone',placeholder:''},email:{show:false,required:false,label:'Email',placeholder:''},address1:{show:true,required:true,label:'House and Street',placeholder:'Full address'},address2:{show:true,required:false,label:'Apartment / Area',placeholder:'Optional address line'},landmark:{show:true,required:false,label:'Nearby Landmark',placeholder:'Optional landmark'},pincode:{show:true,required:true,label:'Postal Code',placeholder:'6-digit pincode'},city:{show:true,required:true,label:'Town / City',placeholder:''},state:{show:true,required:true,label:'State',placeholder:''}},summary:{productImage:false,productName:true,quantity:true,selectedBundle:true,productPrice:true,discount:false,shippingCharge:true,finalTotal:true,couponField:false},protection:{duplicateOrders:false,blackOrders:false,multipleFakeOrders:false,botTraffic:false}};
 let result=await call(base,`/api/stores/${store.id}/settings/cod-form`,'PATCH',codForm);assert.equal(result.response.status,200);assert.equal(result.body.heading,codForm.heading);result=await call(base,`/api/stores/${store.id}/settings`);assert.equal(result.body.codForm.formName,'Primary COD');
 result=await call(base,'/s/nivkara/ritual');assert.doesNotMatch(result.body,/id="cod-form"/);result=await call(base,'/api/public/nivkara/ritual/checkouts','POST',{intent:'open',quantity:1});assert.equal(result.response.status,201);result=await call(base,`/s/nivkara/checkout/${result.body.id}`);assert.match(result.body,/Enter Your Delivery Details/);assert.match(result.body,/Fast delivery across India/);assert.match(result.body,/Confirm COD Order/);assert.match(result.body,/Your Full Name/);assert.match(result.body,/House and Street/);assert.match(result.body,/Apartment \/ Area/);assert.match(result.body,/Nearby Landmark/);assert.doesNotMatch(result.body,/name="email"/);assert.doesNotMatch(result.body,/name="alternatePhone"/);assert.doesNotMatch(result.body,/name="couponCode"/);assert.match(result.body,/autocomplete="off"/);assert.match(result.body,/SAVE_INCOMPLETE=false/);
 result=await call(base,`/api/stores/${store.id}/settings/cod-form`,'PATCH',{enabled:false});assert.equal(result.body.enabled,false);result=await call(base,'/s/nivkara/ritual');assert.doesNotMatch(result.body,/id="cod-form"/);result=await call(base,'/api/public/nivkara/ritual/checkouts','POST',{quantity:1});assert.equal(result.response.status,400);assert.match(result.body.error,/COD Form is disabled/i);
});

test('Settings navigation has the final seven sections and no separate top-level settings modules',async t=>{const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;let result=await call(base,'/');assert.match(result.body,/data-view="settings"><img[^>]*>Settings/);assert.doesNotMatch(result.body,/data-view="cod-form"|data-view="domains"|data-view="pixels"|data-view="delivery"/);result=await call(base,'/app.js');for(const text of ['COD Form','Domain','Pixel','Checkout','Shipping and Delivery','Sales Channels','Customer Privacy'])assert.match(result.body,new RegExp(text));
});
