import test from 'node:test';import assert from 'node:assert/strict';import{createDatabase}from'../src/database.js';import{createApp}from'../src/server.js';
async function call(base,path,method='GET',data){const response=await fetch(base+path,{method,headers:{'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});return{response,body:(response.headers.get('content-type')||'').includes('json')?await response.json():await response.text()};}
async function setup(base){let r=await call(base,'/api/stores','POST',{name:'Nivkara',slug:'nivkara'}),store=r.body;r=await call(base,`/api/stores/${store.id}/products`,'POST',{name:'Oil',slug:'oil',pricePaise:95000,stock:20});const product=r.body;r=await call(base,`/api/stores/${store.id}/pages`,'POST',{productId:product.id,title:'Offer',slug:'offer',body:'Offer'});const page=r.body;await call(base,`/api/stores/${store.id}/pages/${page.id}/publish`,'POST',{});return{store};}
const buyer=(state='Gujarat',quantity=1)=>({quantity,name:'Riya Sharma',phone:'9876543210',address:'12 Green Park Main Road',city:'Ahmedabad',state,pincode:'380001',termsAccepted:true,paymentMethod:'cod',intent:'submit'});
test('shipping methods, zones, free threshold and delivery time affect authoritative checkout and order totals',async t=>{const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;const{store}=await setup(base);let r=await call(base,`/api/stores/${store.id}/shipping-methods`,'POST',{name:'Standard Delivery',chargePaise:4900,enabled:true});assert.equal(r.response.status,201);const method=r.body;r=await call(base,`/api/stores/${store.id}/shipping-zones`,'POST',{name:'Gujarat',state:'Gujarat',shippingMethodId:method.id,pricePaise:7900,enabled:true});assert.equal(r.response.status,201);await call(base,`/api/stores/${store.id}/settings/shipping`,'PATCH',{freeShippingEnabled:true,freeShippingMinimumPaise:99900,minimumDeliveryDays:3,maximumDeliveryDays:5});
 r=await call(base,'/api/public/nivkara/offer/checkouts','POST',buyer());assert.equal(r.response.status,201);assert.equal(r.body.subtotalPaise,95000);assert.equal(r.body.shippingPaise,7900);assert.equal(r.body.totalPaise,102900);assert.equal(r.body.shippingMethod,'Standard Delivery');assert.equal(r.body.deliveryEstimate,'3–5 Days');let order=await call(base,'/api/public/checkouts/'+r.body.id+'/order','POST',{storeId:store.id});assert.equal(order.body.shippingPaise,7900);assert.equal(order.body.totalPaise,102900);
 r=await call(base,'/api/public/nivkara/offer/checkouts','POST',{...buyer('Gujarat',2),phone:'9876543211'});assert.equal(r.body.subtotalPaise,190000);assert.equal(r.body.shippingPaise,0);assert.equal(r.body.totalPaise,190000);
});
test('Shipping and Delivery settings UI exposes real method, free shipping, zones, timing, and partner controls',async t=>{const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;const r=await call(base,'/app.js');for(const text of ['Shipping Methods','Method Name','Shipping Charge','Add Shipping Method','Free Shipping','Minimum Order Value','Shipping Zones','Zone Name','State / Region','Shipping Price','Minimum Delivery Days','Maximum Delivery Days','Delivery Partner List','Test Connection','Disconnect'])assert.match(r.body,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
