import test from'node:test';import assert from'node:assert/strict';import{createDatabase}from'../src/database.js';import{createApp}from'../src/server.js';async function call(base,path,method='GET',data){const response=await fetch(base+path,{method,headers:{'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});return{response,body:(response.headers.get('content-type')||'').includes('json')?await response.json():await response.text()};}async function setup(base){let r=await call(base,'/api/stores','POST',{name:'Nivkara',slug:'nivkara'}),store=r.body;r=await call(base,`/api/stores/${store.id}/products`,'POST',{name:'Oil',slug:'oil',pricePaise:50000,stock:10});const product=r.body;r=await call(base,`/api/stores/${store.id}/pages`,'POST',{productId:product.id,title:'Offer',slug:'offer',body:'Offer'});const page=r.body;await call(base,`/api/stores/${store.id}/pages/${page.id}/publish`,'POST',{});return{store,product,page};}
const buyer={quantity:1,name:'Riya Sharma',phone:'9876543210',address:'12 Green Park Main Road',city:'Delhi',state:'Delhi',pincode:'110001',termsAccepted:true,paymentMethod:'cod',intent:'submit'};
test('Customer Privacy consent gates real pixel loading/events and abandoned/customer data capture',async t=>{const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;const{store}=await setup(base);let r=await call(base,`/api/stores/${store.id}/pixels`,'POST',{name:'Meta Main',platform:'meta',trackingId:'123456789012345',enabled:true});const pixel=r.body;await call(base,`/api/stores/${store.id}/settings/privacy`,'PATCH',{cookieBannerEnabled:true,bannerMessage:'Choose cookies',acceptButtonText:'Accept All',rejectButtonText:'Reject',privacyPolicyLink:'/privacy',marketingTracking:true,advertisingPixels:true,requireMarketingConsent:true,allowCustomerDataCollection:true,allowAbandonedCheckoutData:false,allowVisitorTracking:true,allowPixelTracking:true});
 r=await call(base,'/s/nivkara/offer');const visitorToken=JSON.parse(r.body.match(/VISITOR_TOKEN=("[^"]+")/)?.[1]||'""');assert.ok(visitorToken);assert.match(r.body,/Choose cookies/);assert.match(r.body,/Accept All/);assert.match(r.body,/Reject/);assert.match(r.body,/loadPixels/);assert.match(r.body,/commera2_tracking_consent/);assert.doesNotMatch(r.body,/<script[^>]+connect\.facebook\.net/);
 r=await call(base,`/api/public/stores/${store.id}/pixel-events`,'POST',{eventName:'page_view',pageSlug:'offer',visitorToken,consentGranted:false});assert.equal(r.response.status,400);assert.match(r.body.error,/consent is required/i);r=await call(base,`/api/public/stores/${store.id}/pixel-events`,'POST',{eventName:'page_view',pageSlug:'offer',visitorToken,consentGranted:true});assert.equal(r.body.delivered,1);
 r=await call(base,`/api/stores/${store.id}/pixels/${pixel.id}/verify`,'POST',{});assert.equal(r.body.testResult.events.page_view,'received');assert.equal(r.body.testResult.events.purchase,'no_event_yet');
 r=await call(base,'/api/public/nivkara/offer/checkouts','POST',{quantity:1,name:'Riya',intent:'draft'});assert.equal(r.response.status,400);assert.match(r.body.error,/abandoned checkout data collection is disabled/i);r=await call(base,'/api/public/nivkara/offer/checkouts','POST',buyer);assert.equal(r.response.status,201);
 await call(base,`/api/stores/${store.id}/settings/privacy`,'PATCH',{allowCustomerDataCollection:false});r=await call(base,'/api/public/nivkara/offer/checkouts','POST',{...buyer,phone:'9876543211'});assert.equal(r.response.status,400);assert.match(r.body.error,/customer data collection is disabled/i);
});
test('Pixel settings support names, Custom Pixel endpoint, disabled state, last event, and event view',async t=>{const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;const{store,product,page}=await setup(base);let r=await call(base,`/api/stores/${store.id}/pixels`,'POST',{name:'Custom Attribution',platform:'custom',trackingId:'https://tracker.example/events',enabled:true});assert.equal(r.response.status,201);const pixel=r.body;assert.equal(pixel.name,'Custom Attribution');r=await call(base,'/s/nivkara/offer');const visitorToken=JSON.parse(r.body.match(/VISITOR_TOKEN=("[^"]+")/)?.[1]||'""');assert.ok(visitorToken);await call(base,`/api/public/stores/${store.id}/pixel-events`,'POST',{eventName:'product_page_view',pageSlug:'offer',visitorToken,productId:product.id,pageId:page.id,consentGranted:true});r=await call(base,`/api/stores/${store.id}/pixels`);assert.equal(r.body[0].lastEvent,'product_page_view');r=await call(base,`/api/stores/${store.id}/pixels/${pixel.id}/disable`,'POST',{});assert.equal(r.body.status,'disabled');r=await call(base,'/s/nivkara/offer');assert.doesNotMatch(r.body,/tracker\.example/);r=await call(base,'/app.js');for(const text of ['Pixel Name','Custom Pixel','Last Event','Edit','View Events','No Event Yet'])assert.match(r.body,new RegExp(text));});
