import test from 'node:test';
import assert from 'node:assert/strict';
import { createDatabase } from '../src/database.js';
import { createApp } from '../src/server.js';
async function call(base,path,method='GET',data){const response=await fetch(base+path,{method,headers:{'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});return{response,body:(response.headers.get('content-type')||'').includes('json')?await response.json():await response.text()};}
async function setup(base){let r=await call(base,'/api/stores','POST',{name:'Nivkara',slug:'nivkara'}),store=r.body;r=await call(base,`/api/stores/${store.id}/products`,'POST',{name:'Oil',slug:'oil',pricePaise:50000,stock:10});const product=r.body;r=await call(base,`/api/stores/${store.id}/pages`,'POST',{productId:product.id,title:'Offer',slug:'offer',body:'Offer'});const page=r.body;await call(base,`/api/stores/${store.id}/pages/${page.id}/publish`,'POST',{});return{store,product,page};}
const buyer={quantity:1,name:'Riya Sharma',phone:'9876543210',alternatePhone:'',email:'riya@example.com',address:'12 Green Park Main Road',addressLine2:'Floor 2',landmark:'Near Temple',city:'Delhi',state:'Delhi',pincode:'110001',termsAccepted:true,paymentMethod:'cod',intent:'submit'};

test('Checkout settings control real checkout, coupon, autofill, summary, and abandoned draft behavior',async t=>{const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;const {store}=await setup(base);
 let r=await call(base,`/api/stores/${store.id}/settings/checkout`,'PATCH',{enabled:true,addressAutofill:false,couponField:false,orderSummary:false,captureAbandonedCheckout:false});assert.equal(r.response.status,200);r=await call(base,'/s/nivkara/offer');assert.doesNotMatch(r.body,/id="cod-form"/);let opened=await call(base,'/api/public/nivkara/offer/checkouts','POST',{intent:'open',quantity:1});assert.equal(opened.response.status,201);r=await call(base,`/s/nivkara/checkout/${opened.body.id}`);assert.doesNotMatch(r.body,/name="couponCode"/);assert.match(r.body,/autocomplete="off"/);assert.match(r.body,/SAVE_INCOMPLETE=false/);
 r=await call(base,'/api/public/nivkara/offer/checkouts','POST',{quantity:1,name:'Riya',intent:'draft'});assert.equal(r.response.status,400);assert.match(r.body.error,/abandoned checkout capture is disabled/i);
 r=await call(base,'/api/public/nivkara/offer/checkouts','POST',{...buyer,couponCode:'SAVE10'});assert.equal(r.response.status,400);assert.match(r.body.error,/coupon field is disabled/i);
 r=await call(base,'/api/public/nivkara/offer/checkouts','POST',buyer);assert.equal(r.response.status,201);const checkout=r.body;assert.equal(checkout.addressLine2,'Floor 2');assert.equal(checkout.landmark,'Near Temple');r=await call(base,'/api/public/checkouts/'+checkout.id+'/order','POST',{storeId:store.id});assert.equal(r.response.status,201);
 r=await call(base,`/api/stores/${store.id}/settings/checkout`,'PATCH',{enabled:false});assert.equal(r.body.enabled,false);r=await call(base,'/api/public/nivkara/offer/checkouts','POST',buyer);assert.equal(r.response.status,400);assert.match(r.body.error,/Checkout is disabled/i);
});

test('COD protection switches affect actual blocked-phone and bot checks',async t=>{const app=createApp({db:createDatabase(':memory:'),port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;const {store}=await setup(base);await call(base,`/api/stores/${store.id}/cod-blocklist`,'POST',{phone:buyer.phone,reason:'test'});await call(base,`/api/stores/${store.id}/settings/cod-form`,'PATCH',{protection:{blackOrders:false,botTraffic:false,duplicateOrders:true,multipleFakeOrders:true}});
 let r=await call(base,'/api/public/nivkara/offer/checkouts','POST',{...buyer,website:'bot-filled'});assert.equal(r.response.status,201);r=await call(base,'/api/public/checkouts/'+r.body.id+'/order','POST',{storeId:store.id});assert.equal(r.response.status,201);
});

test('draft checkout becomes abandoned only after the configured inactivity period',async t=>{const db=createDatabase(':memory:'),app=createApp({db,port:0});await app.start();t.after(()=>app.stop());const base=`http://127.0.0.1:${app.port}`;const {store}=await setup(base);let r=await call(base,`/api/stores/${store.id}/settings/checkout`,'PATCH',{abandonedCheckoutTimeoutMinutes:5});assert.equal(r.body.abandonedCheckoutTimeoutMinutes,5);r=await call(base,'/api/public/nivkara/offer/checkouts','POST',{intent:'open',quantity:1});assert.equal(r.response.status,201);const sessionId=r.body.id;r=await call(base,`/api/stores/${store.id}/dashboard`);assert.equal(r.body.abandoned.length,0);db.prepare("UPDATE checkout_sessions SET updated_at=datetime('now','-6 minutes') WHERE store_id=? AND id=?").run(store.id,sessionId);r=await call(base,`/api/stores/${store.id}/dashboard`);assert.equal(r.body.abandoned.length,1);assert.equal(r.body.ordersWorkspace.abandonedCount,1);});
