const row=value=>value?Object.fromEntries(Object.entries(value).map(([key,item])=>[key.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase()),item])):null;
const clean=value=>String(value??'').trim().replace(/\s+/g,' ');
const hasMeaningfulReviewContent=value=>{const text=clean(value),lettersAndNumbers=text.match(/[\p{L}\p{N}]/gu)||[];return lettersAndNumbers.length>=2||/\p{Extended_Pictographic}/u.test(text);};
const imageTypes=new Set(['image/jpeg','image/png','image/webp']);
const validateReviewDate=value=>{if(!value)return;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw Error('Review Date must use YYYY-MM-DD');const date=new Date(`${value}T00:00:00Z`);if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==value)throw Error('Review Date must be a valid calendar date');if(value>new Date().toISOString().slice(0,10))throw Error('Review Date cannot be in the future');};
const usableReviewDate=value=>{if(!value||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(`${value}T00:00:00Z`);return !Number.isNaN(date.getTime())&&date.toISOString().slice(0,10)===value&&value<=new Date().toISOString().slice(0,10);};

export class ReviewService{
  constructor(db){this.db=db;}
  #store(storeId){if(!this.db.prepare('SELECT id FROM stores WHERE id=?').get(storeId))throw Error('Store not found');}
  #product(storeId,productId){const product=row(this.db.prepare('SELECT * FROM products WHERE store_id=? AND id=?').get(storeId,productId));if(!product)throw Error('Product not found');if(!product.active)throw Error('Product is not active');return product;}
  #validate(input){const customerName=clean(input.customerName),rating=Number(input.rating),title=clean(input.title),text=clean(input.text);if(customerName.length<2||!/\p{L}/u.test(customerName))throw Error('Customer Name must contain at least one letter');if(!Number.isInteger(rating)||rating<1||rating>5)throw Error('Rating must be between 1 and 5 stars');if(!hasMeaningfulReviewContent(text))throw Error('Review Text must contain readable feedback or an emoji');if(title&&!hasMeaningfulReviewContent(title))throw Error('Review Title must contain readable text or an emoji');if(title.length>160)throw Error('Review Title must be 160 characters or fewer');if(text.length>5000)throw Error('Review Text must be 5000 characters or fewer');return{customerName,rating,title,text};}
  #images(images=[]){if(!Array.isArray(images))throw Error('Review Images must be an array');if(images.length>5)throw Error('A review can have at most 5 images');return images.map((image,index)=>{const type=clean(image.type).toLowerCase(),name=clean(image.name)||`review-${index+1}`.slice(0,120),data=String(image.data||'').replace(/^data:[^;]+;base64,/, '').replace(/\s/g,'');if(!imageTypes.has(type))throw Error('Review images must be JPEG, PNG, or WebP');if(!/^[A-Za-z0-9+/]+={0,2}$/.test(data))throw Error('Review image data is invalid');const bytes=Buffer.from(data,'base64');if(!bytes.length||bytes.length>1024*1024)throw Error('Each review image must be 1 MB or smaller');return{name:name.slice(0,120),type,data,index};});}
  #insertImages(reviewId,images){const insert=this.db.prepare('INSERT INTO review_images (review_id,file_name,mime_type,image_base64,sort_order) VALUES (?,?,?,?,?)');for(const image of images)insert.run(reviewId,image.name,image.type,image.data,image.index);}
  #output(value){const review=row(value);if(!review)return null;review.text=review.reviewText;delete review.reviewText;review.reviewDateInvalid=Boolean(review.reviewDate&&!usableReviewDate(review.reviewDate));if(review.reviewDateInvalid)review.reviewDate=null;review.storedSource=review.source;if(review.importBatchId)review.source='bulk';review.verifiedPurchase=Boolean(review.verifiedPurchase);review.featured=Boolean(review.featured);review.images=this.db.prepare('SELECT id,file_name,mime_type,image_base64,sort_order FROM review_images WHERE review_id=? ORDER BY sort_order,id').all(review.id).map(image=>{const item=row(image);return{id:item.id,name:item.fileName,type:item.mimeType,dataUrl:`data:${item.mimeType};base64,${item.imageBase64}`,sortOrder:item.sortOrder};});return review;}
  createConsumer(storeId,productId,input){const product=this.#product(storeId,Number(productId)),review=this.#validate(input),images=this.#images(input.images);this.db.exec('BEGIN IMMEDIATE');try{const result=this.db.prepare("INSERT INTO reviews (store_id,product_id,customer_name,rating,title,review_text,source,status) VALUES (?,?,?,?,?,?,'consumer','pending')").run(storeId,product.id,review.customerName,review.rating,review.title,review.text);const id=Number(result.lastInsertRowid);this.#insertImages(id,images);this.db.exec('COMMIT');return this.get(storeId,id);}catch(error){this.db.exec('ROLLBACK');throw error;}}
  createManual(storeId,input){const product=this.#product(storeId,Number(input.productId)),review=this.#validate(input),images=this.#images(input.images),status=clean(input.status).toLowerCase(),reviewDate=clean(input.reviewDate);if(input.authenticityConfirmed!==true)throw Error('Confirm that this is authentic customer feedback');if(!['approved','draft'].includes(status))throw Error('Manual review status must be Approved or Draft');validateReviewDate(reviewDate);this.db.exec('BEGIN IMMEDIATE');try{const result=this.db.prepare("INSERT INTO reviews (store_id,product_id,customer_name,rating,title,review_text,source,status,review_date) VALUES (?,?,?,?,?,?,'manual',?,NULLIF(?,''))").run(storeId,product.id,review.customerName,review.rating,review.title,review.text,status,reviewDate);const id=Number(result.lastInsertRowid);this.#insertImages(id,images);this.db.exec('COMMIT');return this.get(storeId,id);}catch(error){this.db.exec('ROLLBACK');throw error;}}
  updateManual(storeId,id,input){const current=this.get(storeId,id);if(current.source!=='manual')throw Error('Only manually added reviews can be edited');if(input.authenticityConfirmed!==true)throw Error('Confirm that this is authentic customer feedback');const product=this.#product(storeId,Number(input.productId??current.productId)),review=this.#validate({...current,...input,text:input.text??current.text}),status=clean(input.status??current.status).toLowerCase(),reviewDate=clean(input.reviewDate??current.reviewDate);if(!['approved','draft'].includes(status))throw Error('Manual review status must be Approved or Draft');validateReviewDate(reviewDate);const images=input.images===undefined?null:this.#images(input.images);this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare("UPDATE reviews SET product_id=?,customer_name=?,rating=?,title=?,review_text=?,status=?,review_date=NULLIF(?,''),updated_at=CURRENT_TIMESTAMP WHERE store_id=? AND id=?").run(product.id,review.customerName,review.rating,review.title,review.text,status,reviewDate,storeId,id);if(images){this.db.prepare('DELETE FROM review_images WHERE review_id=?').run(id);this.#insertImages(id,images);}this.db.exec('COMMIT');return this.get(storeId,id);}catch(error){this.db.exec('ROLLBACK');throw error;}}
  deleteManual(storeId,id){const review=this.get(storeId,id);if(review.source!=='manual')throw Error('Only manually added reviews can be deleted');this.db.prepare('DELETE FROM reviews WHERE store_id=? AND id=?').run(storeId,id);return{deleted:true,id};}
  delete(storeId,id){this.get(storeId,id);this.db.prepare('DELETE FROM reviews WHERE store_id=? AND id=?').run(storeId,id);return{deleted:true,id};}
  updateImported(storeId,id,input){const review=this.get(storeId,id);if(review.source!=='bulk')throw Error('Only bulk-imported reviews use imported review controls');const featured=input.featured===undefined?review.featured:Boolean(input.featured),reply=input.reply===undefined?review.merchantReply:clean(input.reply),replyAt=input.replyAt===undefined?review.replyAt:clean(input.replyAt);if(reply.length>2000)throw Error('Merchant reply must be 2000 characters or fewer');if(replyAt&&!/^\d{4}-\d{2}-\d{2}$/.test(replyAt))throw Error('Reply date must use YYYY-MM-DD');this.db.prepare("UPDATE reviews SET featured=?,merchant_reply=?,reply_at=NULLIF(?,''),updated_at=CURRENT_TIMESTAMP WHERE store_id=? AND id=?").run(featured?1:0,reply,replyAt,storeId,id);return this.get(storeId,id);}
  get(storeId,id){this.#store(storeId);const value=this.db.prepare('SELECT r.*,p.name product_name FROM reviews r JOIN products p ON p.id=r.product_id WHERE r.store_id=? AND r.id=?').get(storeId,id);if(!value)throw Error('Review not found');return this.#output(value);}
  list(storeId,{source=null,status=null}={}){this.#store(storeId);let sql='SELECT r.*,p.name product_name FROM reviews r JOIN products p ON p.id=r.product_id WHERE r.store_id=?',args=[storeId];if(source==='bulk')sql+=' AND r.import_batch_id IS NOT NULL';else if(source==='manual')sql+=" AND r.source='manual' AND r.import_batch_id IS NULL";else if(source){sql+=' AND r.source=?';args.push(source);}if(status){sql+=' AND r.status=?';args.push(status);}sql+=' ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC';return this.db.prepare(sql).all(...args).map(value=>this.#output(value));}
  moderate(storeId,id,status){const review=this.get(storeId,id),next=clean(status).toLowerCase();if(!['consumer','bulk'].includes(review.source))throw Error('Only consumer and bulk-imported reviews use Approve / Disapprove moderation');if(!['pending','approved','disapproved'].includes(next))throw Error('Review status must be Pending, Approved, or Disapproved');this.db.prepare('UPDATE reviews SET status=?,updated_at=CURRENT_TIMESTAMP WHERE store_id=? AND id=?').run(next,storeId,id);return this.get(storeId,id);}
  bulkModerate(storeId,reviewIds,status){if(!Array.isArray(reviewIds)||!reviewIds.length)throw Error('Select at least one review');const ids=[...new Set(reviewIds.map(Number))];this.db.exec('BEGIN IMMEDIATE');try{const updated=ids.map(id=>this.moderate(storeId,id,status));this.db.exec('COMMIT');return updated;}catch(error){this.db.exec('ROLLBACK');throw error;}}
  publicProduct(storeId,productId){this.#product(storeId,Number(productId));const reviews=this.db.prepare("SELECT r.*,p.name product_name FROM reviews r JOIN products p ON p.id=r.product_id WHERE r.store_id=? AND r.product_id=? AND r.status='approved' ORDER BY r.featured DESC,COALESCE(r.review_date,r.created_at) DESC,r.id DESC").all(storeId,Number(productId)).map(value=>this.#output(value)),breakdown={'1':0,'2':0,'3':0,'4':0,'5':0};let total=0;for(const review of reviews){breakdown[String(review.rating)]++;total+=review.rating;}return{summary:{count:reviews.length,average:reviews.length?Math.round(total/reviews.length*10)/10:0,breakdown},reviews};}
}
