const clean=value=>String(value??'').trim();
const bool=(value,fallback)=>{
  if (value === undefined) return fallback;
  if (typeof value === "string") {
    const parsed = value.trim().toLowerCase();
    if (["false","0","off","no"].includes(parsed)) return false;
    if (["true","1","on","yes"].includes(parsed)) return true;
  }
  return Boolean(value);
};
const clone=value=>structuredClone(value);
const merge=(base,patch)=>{const result=clone(base);for(const [key,value] of Object.entries(patch||{})){if(value&&typeof value==='object'&&!Array.isArray(value)&&result[key]&&typeof result[key]==='object'&&!Array.isArray(result[key]))result[key]=merge(result[key],value);else result[key]=value;}return result;};
const field=(label,{show=true,required=false,placeholder=''}={})=>({show,required,label,placeholder});
export const defaultSettings={
 codForm:{enabled:true,formName:'Default COD Form',heading:'Complete Your Delivery Details',subheading:'',submitButtonText:'Place COD Order',addressAutofill:true,saveIncompleteCheckout:true,buttonEnabled:true,fields:{fullName:field('Full Name',{required:true}),phone:field('Phone Number',{required:true}),alternatePhone:field('Alternate Phone',{show:true}),email:field('Email',{show:true}),address1:field('Address Line 1',{required:true,placeholder:'House or building, street'}),address2:field('Address Line 2',{show:true,placeholder:'Area, locality, floor or apartment (optional)'}),landmark:field('Landmark',{show:false}),pincode:field('Pincode',{required:true}),city:field('City',{required:true}),state:field('State',{required:true}),country:field('Country',{required:true})},otp:{enabled:false,requiredForCod:true,length:6,expiryMinutes:5,resendDelaySeconds:30,maxAttempts:5,maxResends:3,verificationPosition:'before_order',provider:'custom',allowPhoneChange:true},summary:{productImage:true,productName:true,quantity:true,selectedBundle:true,productPrice:true,discount:true,shippingCharge:true,finalTotal:true,couponField:true},protection:{duplicateOrders:true,blackOrders:true,multipleFakeOrders:true,botTraffic:true,botProtection:{enabled:true,rateLimiting:true,deviceSessionCheck:true,behaviorDetection:true,invisibleChallenge:false,captchaSuspiciousTraffic:false,ipReputationCheck:false,blockKnownBadIps:false,checkoutToken:false,honeypot:true,otpSuspiciousTraffic:true,highRiskAction:'require_otp',criticalRiskAction:'block',ipCheckoutLimit:10,ipWindowMinutes:10,deviceAttemptLimit:5,deviceWindowMinutes:30}}},
 checkout:{enabled:true,addressAutofill:true,couponField:true,orderSummary:true,captureAbandonedCheckout:true,abandonedCheckoutTimeoutMinutes:30,customerInformation:{fullName:'required',phone:'required',email:'optional',address:'required',city:'required',state:'required',pincode:'required'},summary:{productImage:true,productName:true,quantity:true,bundle:true,discount:true,shipping:true,total:true}},
 shipping:{freeShippingEnabled:false,freeShippingMinimumPaise:0,minimumDeliveryDays:3,maximumDeliveryDays:5},
 privacy:{cookieBannerEnabled:false,bannerMessage:'We use cookies to improve checkout and measure marketing performance.',acceptButtonText:'Accept',rejectButtonText:'Reject',privacyPolicyLink:'/privacy',analyticsTracking:true,marketingTracking:true,advertisingPixels:true,requireAnalyticsConsent:false,requireMarketingConsent:false,allowCustomerDataCollection:true,allowAbandonedCheckoutData:true,allowVisitorTracking:true,allowPixelTracking:true,visitorSessionTimeoutMinutes:5}
};
const columns={codForm:'cod_form_json',checkout:'checkout_json',shipping:'shipping_json',privacy:'privacy_json'};
function parse(value,fallback){try{return merge(fallback,JSON.parse(value||'{}'));}catch{return clone(fallback);}}
function nonempty(value,message){if(!clean(value))throw Error(message);return clean(value);}
function validateField(key,value){const result={show:bool(value.show,true),required:bool(value.required,false),label:nonempty(value.label,`${key} label is required`),placeholder:clean(value.placeholder)};if(['fullName','phone','address1','pincode','city','state','country'].includes(key)){if(!result.show||!result.required)throw Error(`${key} is required for COD delivery and cannot be hidden`);}if(result.required&&!result.show)throw Error(`${key} cannot be required while hidden`);return result;}
export class SettingsService{
 constructor(db){this.db=db;}
 #store(id){if(!this.db.prepare('SELECT id FROM stores WHERE id=?').get(id))throw Error('Store not found');}
 #ensure(storeId){this.#store(storeId);this.db.prepare('INSERT INTO store_settings(store_id) VALUES(?) ON CONFLICT(store_id) DO NOTHING').run(storeId);return this.db.prepare('SELECT * FROM store_settings WHERE store_id=?').get(storeId);}
 get(storeId){const row=this.#ensure(storeId);return{codForm:parse(row.cod_form_json,defaultSettings.codForm),checkout:parse(row.checkout_json,defaultSettings.checkout),shipping:parse(row.shipping_json,defaultSettings.shipping),privacy:parse(row.privacy_json,defaultSettings.privacy)};}
 update(storeId,module,patch){const column=columns[module];if(!column)throw Error('Unsupported settings module');const current=this.get(storeId)[module];let next=merge(current,patch||{});if(module==='codForm')next=this.#cod(next);if(module==='checkout')next=this.#checkout(next);if(module==='shipping')next=this.#shipping(next);if(module==='privacy')next=this.#privacy(next);this.db.prepare(`UPDATE store_settings SET ${column}=?,updated_at=CURRENT_TIMESTAMP WHERE store_id=?`).run(JSON.stringify(next),storeId);return this.get(storeId)[module];}
 #cod(value){value.enabled=bool(value.enabled,true);value.formName=nonempty(value.formName,'Form Name is required');value.heading=nonempty(value.heading,'Form Heading is required');value.subheading=clean(value.subheading);value.submitButtonText=nonempty(value.submitButtonText,'Submit Button Text is required');value.addressAutofill=bool(value.addressAutofill,true);value.saveIncompleteCheckout=bool(value.saveIncompleteCheckout,true);value.buttonEnabled=bool(value.buttonEnabled,true);for(const key of Object.keys(defaultSettings.codForm.fields))value.fields[key]=validateField(key,value.fields[key]);for(const key of Object.keys(defaultSettings.codForm.summary))value.summary[key]=bool(value.summary[key],true);const otp=value.otp||{};for(const key of ['enabled','requiredForCod','allowPhoneChange'])otp[key]=bool(otp[key],defaultSettings.codForm.otp[key]);otp.length=Number(otp.length);otp.expiryMinutes=Number(otp.expiryMinutes);otp.resendDelaySeconds=Number(otp.resendDelaySeconds);otp.maxAttempts=Number(otp.maxAttempts);otp.maxResends=Number(otp.maxResends);if(![4,6].includes(otp.length))throw Error('OTP length must be 4 or 6 digits');if(!Number.isInteger(otp.expiryMinutes)||otp.expiryMinutes<1||otp.expiryMinutes>30)throw Error('OTP expiry must be between 1 and 30 minutes');if(!Number.isInteger(otp.resendDelaySeconds)||otp.resendDelaySeconds<10||otp.resendDelaySeconds>300)throw Error('OTP resend delay must be between 10 and 300 seconds');if(!Number.isInteger(otp.maxAttempts)||otp.maxAttempts<1||otp.maxAttempts>10)throw Error('Maximum OTP attempts must be between 1 and 10');if(!Number.isInteger(otp.maxResends)||otp.maxResends<0||otp.maxResends>10)throw Error('Maximum OTP resends must be between 0 and 10');if(!['before_checkout','before_order'].includes(otp.verificationPosition))throw Error('Invalid OTP verification position');otp.provider=nonempty(otp.provider,'OTP provider is required');value.otp=otp;for(const key of ['duplicateOrders','blackOrders','multipleFakeOrders','botTraffic'])value.protection[key]=bool(value.protection[key],true);const bot=value.protection.botProtection||{};for(const key of ['enabled','rateLimiting','deviceSessionCheck','behaviorDetection','invisibleChallenge','captchaSuspiciousTraffic','ipReputationCheck','blockKnownBadIps','checkoutToken','honeypot','otpSuspiciousTraffic'])bot[key]=bool(bot[key],defaultSettings.codForm.protection.botProtection[key]);for(const key of ['ipCheckoutLimit','ipWindowMinutes','deviceAttemptLimit','deviceWindowMinutes']){bot[key]=Number(bot[key]);if(!Number.isInteger(bot[key])||bot[key]<1||bot[key]>1000)throw Error(`${key} must be a positive whole number`);}if(!['allow','challenge','require_otp','block'].includes(bot.highRiskAction))throw Error('Invalid high-risk traffic action');if(!['challenge','require_otp','block'].includes(bot.criticalRiskAction))throw Error('Invalid critical-risk traffic action');value.protection.botProtection=bot;return value;}
 #checkout(value){for(const key of ['enabled','addressAutofill','couponField','orderSummary','captureAbandonedCheckout'])value[key]=bool(value[key],true);value.abandonedCheckoutTimeoutMinutes=Number(value.abandonedCheckoutTimeoutMinutes??30);if(!Number.isInteger(value.abandonedCheckoutTimeoutMinutes)||value.abandonedCheckoutTimeoutMinutes<5||value.abandonedCheckoutTimeoutMinutes>1440)throw Error('Abandoned checkout timeout must be between 5 and 1440 minutes');for(const key of Object.keys(defaultSettings.checkout.customerInformation)){if(!['required','optional','hidden'].includes(value.customerInformation[key]))throw Error(`Invalid ${key} checkout information setting`);}for(const key of Object.keys(defaultSettings.checkout.summary))value.summary[key]=bool(value.summary[key],true);return value;}
 #shipping(value){value.freeShippingEnabled=bool(value.freeShippingEnabled,false);value.freeShippingMinimumPaise=Number(value.freeShippingMinimumPaise||0);value.minimumDeliveryDays=Number(value.minimumDeliveryDays);value.maximumDeliveryDays=Number(value.maximumDeliveryDays);if(!Number.isInteger(value.freeShippingMinimumPaise)||value.freeShippingMinimumPaise<0)throw Error('Free shipping minimum must be a non-negative integer in paise');if(value.freeShippingEnabled&&value.freeShippingMinimumPaise<1)throw Error('Minimum Order Value is required when free shipping is enabled');if(!Number.isInteger(value.minimumDeliveryDays)||!Number.isInteger(value.maximumDeliveryDays)||value.minimumDeliveryDays<0||value.maximumDeliveryDays<value.minimumDeliveryDays)throw Error('Delivery time range is invalid');return value;}
 #privacy(value){for(const key of ['cookieBannerEnabled','analyticsTracking','marketingTracking','advertisingPixels','requireAnalyticsConsent','requireMarketingConsent','allowCustomerDataCollection','allowAbandonedCheckoutData','allowVisitorTracking','allowPixelTracking'])value[key]=bool(value[key],defaultSettings.privacy[key]);value.visitorSessionTimeoutMinutes=Number(value.visitorSessionTimeoutMinutes??5);if(!Number.isInteger(value.visitorSessionTimeoutMinutes)||value.visitorSessionTimeoutMinutes<1||value.visitorSessionTimeoutMinutes>60)throw Error('Live visitor timeout must be between 1 and 60 minutes');value.bannerMessage=clean(value.bannerMessage);value.acceptButtonText=clean(value.acceptButtonText);value.rejectButtonText=clean(value.rejectButtonText);value.privacyPolicyLink=clean(value.privacyPolicyLink);if(value.cookieBannerEnabled&&(!value.bannerMessage||!value.acceptButtonText||!value.rejectButtonText||!value.privacyPolicyLink))throw Error('Cookie banner message, buttons, and Privacy Policy Link are required');if(value.privacyPolicyLink){if(!value.privacyPolicyLink.startsWith('/')){try{const url=new URL(value.privacyPolicyLink);if(!['http:','https:'].includes(url.protocol))throw Error();}catch{throw Error('Privacy Policy Link must be a valid HTTP, HTTPS, or local path');}}}return value;}
}
